#FROM openjdk:8-jdk-alpine
## Add a volume pointing to /tmp
#VOLUME /tmp
#
#EXPOSE 8080
## The application's jar file
#ARG JAR_FILE=target/process-manager-api-1.0.0-SNAPSHOT.jar
#
## Add the application's jar to the container
#ADD ${JAR_FILE} process-api.jar
## Run the jar file
#ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/process-api.jar"]
