version: '3'

services:
# DISCOVERY SERVICE
  # mongodb
  mongodb:
    image: mongo:latest
    container_name: 'pro-mongodb'
    #        restart: always
    ports:
      - '27017:27017'
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: 'root'
    #      MONGO_INITDB_ROOT_PASSWORD: 'root'
    volumes:
      - '/$home/workspace/process/data/mongo:/data/db'

  discovery:
    build:
      context: eurekaNamingServer
      dockerfile: Dockerfile
    ports:
      - 8761:8761

# API GATEWAY
  gateway:
    build:
      context: zuulApiGateway
      dockerfile: Dockerfile
    ports:
      - 8762:8762
    depends_on:
      - discovery

  process-manager-ui:
#    image: docker.io/aparnachoubey/planage_process-manager-ui:0.1.6
    build:
      context: process-manager-ui
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - discovery
#    container_name: angularcontainer  # Container name

  process-manager-boot:
#     image: docker.io/aparnachoubey/planage_process-manager-boot:0.1.6
     build:
      context: process-spring-boot
      dockerfile: Dockerfile
     ports:
       - 8080:8080
     depends_on:
       - discovery
       - mongodb

  process-nodejs:
#    image: docker.io/aparnachoubey/planage_process-nodejs:0.1.6
    build:
      context: node
      dockerfile: Dockerfile
    ports:
      - 3000:3000

# # mongodb
#   mongodb:
#     image: 'mongo'
#     container_name: 'process-mongodb'
#     #        restart: always
#     ports:
#       - '27017:27017'
# #    environment:
# #      MONGO_INITDB_ROOT_USERNAME: 'root'
# #      MONGO_INITDB_ROOT_PASSWORD: 'root'
#     volumes:
#       - '/$home/workspace/process/data/mongo:/data/db'


#   SERVICES

  # rabbitmq
#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: 'planage-rabbitmq'
##        restart: always
##    environment:
##      RABBITMQ_DEFAULT_USER: ''
##      RABBITMQ_DEFAULT_PASS: 'root'
##      RABBITMQ_DEFAULT_VHOST: '/'
#    ports:
#      - '15672:15672'
#      - '5672:5672'
