version: '3'
services:
  angular-ui:
   build: product-manager-ui
   ports:
     - 8083:8083
   container_name: angularcontainer  # Container name  
  
  product-api:
    build: api
    ports:
      - 8084:8084
    depends_on: 
      - mongodb
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
     image: mongo
 #    environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
   #    - MONGO_INITDB_ROOT_PASSWORD=pass
     ports:
       - 27017:27017
     volumes:
       - $HOME/workspace/product/ProductsDB:/data/db
