FROM openjdk:8-jdk-alpine
# Add a volume pointing to /tmp
VOLUME /tmp
# Make port 8085 available to the world outside this container
EXPOSE 8085
# The application's jar file
ARG JAR_FILE=target/api-1.0.0-SNAPSHOT.jar
# Add the application's jar to the container
ADD ${JAR_FILE} sprint.jar
# Run the jar file
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/sprint.jar"]
