version: '3'
services:
  scheduler:
   build: promanager-ui
   ports:
     - 8082:8082
   container_name: angularcontainer

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - $HOME/workspace/product/mydb:/data/db
  
  program-api:
    build: api
    ports:
      - 8081:8081
    depends_on:
      - mongodb
      - rabbitmq
    

